language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolshain-r-test
    packages:
    - cmake
    - g++-4.9
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
