language: cpp
compiler:
  - gcc
before_install:
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
  - sudo sh cmake-3.8.0-Linux-x86_64.sh --skip-license --prefix=/usr
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
