version: 1.0.{build}
image:
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2013
init:
- cmd: git clone https://github.com/google/googletest.git C:\projects\googletest
install:
- cmd: >-
    cd C:\projects\googletest

    mkdir build && cd build

    cmake ..

    msbuild googletest-distribution.sln

    msbuild INSTALL.vcxproj
before_build:
- cmd: >-
    cd C:\projects\bitsetcontainer

    mkdir build && cd build

    cmake .. -DGTEST_LIBRARY="C:\Program Files (x86)\googletest-distribution\lib\gtestd.lib" -DGTEST_MAIN_LIBRARY="C:\Program Files (x86)\googletest-distribution\lib\gtest_maind.lib" -DGTEST_INCLUDE_DIR="C:\Program Files (x86)\googletest-distribution\include"
build:
  project: build/BitsetContainer.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - bkonz@unomaha.edu
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false