version: 1.0.{build}
image:
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2013
init:
- cmd: git clone https://github.com/google/googletest.git C:\projects\googletest
install:
- cmd: >-
    cd C:\projects\googletest

    mkdir build && cd build

    cmake ..

    msbuild googletest-distribution.sln

    msbuild INSTALL.vcxproj

    cd C:\projects\bitsetcontainer

    mkdir build && cd build

    cmake ..
build:
  project: BitsetContainer.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - bkonz@unomaha.edu
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false